import { useEffect, useState } from "react";
import { useSearchParams } from "react-router";
import { cn } from "@/lib/cn";
import { PageHeader } from "@/components/layout/PageHeader";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { StatusBadge, Badge } from "@/components/ui/Badge";
import { DataTable } from "@/components/ui/DataTable";
import type { Column } from "@/components/ui/DataTable";
import { Field, Input, Select } from "@/components/ui/Field";
import { Modal } from "@/components/ui/Modal";
import { SkeletonRows, EmptyState, ErrorState } from "@/components/ui/States";
import { useToast } from "@/components/ui/Toast";
import { useApi, mutate, fmtPKR, timeAgo, type ApiInvoice, type ApiInvoiceDetail, type ApiQuote } from "@/lib/api";
import { Banknote, FileText, Printer, Receipt, Send } from "@/icons";

const FILTERS = ["all", "open", "Partially Paid", "Paid", "Overdue", "Cancelled"] as const;
const fmtDate = (d: string | null) => (d ? new Date(d + "T00:00:00").toLocaleDateString("en-PK", { day: "2-digit", month: "short", year: "numeric" }) : "—");

function printInvoice(inv: ApiInvoiceDetail) {
  const rows = (inv.items ?? [])
    .map((i, n) => `<tr><td>${n + 1}</td><td>${i.name ?? "Item"}</td><td class="r">${i.qty ?? 1}</td><td class="r">${fmtPKR(i.price ?? 0)}</td><td class="r">${fmtPKR((i.price ?? 0) * (i.qty ?? 1))}</td></tr>`)
    .join("");
  const pays = (inv.payments ?? [])
    .map((p) => `<tr><td>${fmtDate(p.created_at.slice(0, 10))}</td><td>${p.method}</td><td>${p.reference ?? ""}</td><td class="r">${fmtPKR(p.amount)}</td></tr>`)
    .join("");
  const w = window.open("", "_blank", "width=860,height=900");
  if (!w) return;
  w.document.write(`<!doctype html><html><head><title>${inv.ref}</title><style>
    *{box-sizing:border-box;margin:0}body{font-family:Inter,system-ui,sans-serif;color:#182230;padding:48px}
    header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #1d7a3d;padding-bottom:20px}
    h1{font-size:22px}h1 span{color:#1d7a3d}.co{font-size:12px;color:#5b6472;text-align:right;line-height:1.7}
    .meta{display:flex;gap:48px;margin:22px 0;font-size:13px}.meta b{display:block;font-size:11px;text-transform:uppercase;color:#5b6472;margin-bottom:4px}
    table{width:100%;border-collapse:collapse;font-size:13px}th{text-align:left;font-size:11px;text-transform:uppercase;color:#5b6472;border-bottom:1px solid #d7dbe2;padding:8px 6px}
    td{padding:8px 6px;border-bottom:1px solid #eef0f4}.r{text-align:right}
    tfoot td{border:none;font-weight:600}.tot{width:280px;margin-left:auto;margin-top:14px;font-size:13px}.tot div{display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #eef0f4}
    .tot .due{font-weight:800;border-bottom:2px solid #1d7a3d;font-size:15px}
    .pay{margin-top:34px}.pay h3{font-size:12px;text-transform:uppercase;color:#5b6472;margin-bottom:8px}
    footer{margin-top:44px;font-size:11px;color:#5b6472;border-top:1px solid #d7dbe2;padding-top:14px;display:flex;justify-content:space-between}
    .stamp{display:inline-block;border:2px solid ${inv.balance <= 0 ? "#1d7a3d" : "#b45309"};color:${inv.balance <= 0 ? "#1d7a3d" : "#b45309"};padding:4px 12px;border-radius:6px;font-weight:800;font-size:12px;transform:rotate(-4deg)}
  </style></head><body>
    <header><h1>WOODEX <span>INVOICE</span></h1><div class="co"><b>Woodex Furniture</b>Johar Town, Lahore · Pakistan<br>+92 300 0000000 · sales@woodex.pk<br>NTR: 1234567-8</div></header>
    <div class="meta"><div><b>Invoice</b>${inv.ref}</div><div><b>Status</b><span class="stamp">${inv.status.toUpperCase()}</span></div><div><b>Issued</b>${fmtDate(inv.createdAt.slice(0, 10))}</div><div><b>Due</b>${fmtDate(inv.due)}</div></div>
    <div class="meta"><div><b>Bill to</b>${inv.customer}${inv.notes ? "<br><span style='color:#5b6472'>" + inv.notes + "</span>" : ""}</div></div>
    <table><thead><tr><th>#</th><th>Item</th><th class="r">Qty</th><th class="r">Unit</th><th class="r">Amount</th></tr></thead><tbody>${rows}</tbody></table>
    <div class="tot"><div><span>Subtotal</span><span>${fmtPKR(inv.subtotal)}</span></div><div><span>Discount</span><span>− ${fmtPKR(inv.discount)}</span></div><div><span>Tax</span><span>${fmtPKR(inv.tax)}</span></div><div><span>Shipping & installation</span><span>${fmtPKR(inv.shipping)}</span></div><div class="due"><span>Total</span><span>${fmtPKR(inv.total)}</span></div><div><span>Paid</span><span>${fmtPKR(inv.paid)}</span></div><div><span>Balance due</span><span>${fmtPKR(inv.balance)}</span></div></div>
    ${pays ? `<div class="pay"><h3>Payments received</h3><table><thead><tr><th>Date</th><th>Method</th><th>Reference</th><th class="r">Amount</th></tr></thead><tbody>${pays}</tbody></table></div>` : ""}
    <footer><span>Bank transfer: Meezan Bank · Woodex Furniture · ACCT 0000-123456 · Advance 50% required before production starts.</span><span>${inv.ref} · Generated by Woodex Agency OS</span></footer>
    <script>window.onload=()=>window.print()</script></body></html>`);
  w.document.close();
}

export default function Invoices() {
  const [filter, setFilter] = useState<(typeof FILTERS)[number]>("all");
  const { data, loading, error, reload } = useApi<{ total: number; collected: number; outstanding: number; items: ApiInvoice[] }>(
    `/api/invoices${filter !== "all" ? `?status=${encodeURIComponent(filter)}` : ""}`, 15000);
  const { push } = useToast();
  const [detail, setDetail] = useState<ApiInvoiceDetail | null>(null);
  const [pay, setPay] = useState({ amount: "", method: "Bank transfer", reference: "" });
  const [issueOpen, setIssueOpen] = useState(false);
  const [params] = useSearchParams();
  useEffect(() => { if (params.get("issue") === "1") setIssueOpen(true); }, [params]);
  const [busy, setBusy] = useState(false);
  const quotesApi = useApi<{ items: ApiQuote[] }>("/api/quotes", 30000);
  const issuable = (quotesApi.data?.items ?? []).filter((q) => ["Approved", "Sent", "Viewed", "Negotiation", "Revised"].includes(q.status));

  const openDetail = async (inv: ApiInvoice) => {
    try {
      const res = await fetch(`/api/invoices/${inv.id}`);
      if (!res.ok) throw new Error("could not load invoice");
      setDetail(await res.json());
      setPay({ amount: String(inv.balance || ""), method: "Bank transfer", reference: "" });
    } catch (e) { push({ tone: "danger", title: "Load failed", desc: e instanceof Error ? e.message : String(e) }); }
  };

  const recordPayment = async () => {
    if (!detail) return;
    setBusy(true);
    try {
      const res = await fetch(`/api/invoices/${detail.id}/payments`, {
        method: "POST", headers: { "content-type": "application/json" },
        body: JSON.stringify({ amount: Number(pay.amount), method: pay.method, reference: pay.reference || undefined }),
      });
      if (!res.ok) throw new Error((await res.json()).error ?? "payment rejected");
      const d = (await res.json()) as ApiInvoiceDetail;
      setDetail(d);
      push({ tone: "success", title: `Payment recorded · ${fmtPKR(Number(pay.amount))}`, desc: d.status === "Paid" ? `${detail.ref} settled in full.` : `${detail.ref} now ${d.status.toLowerCase()}.` });
      reload();
    } catch (e) { push({ tone: "danger", title: "Payment failed", desc: e instanceof Error ? e.message : String(e) }); }
    finally { setBusy(false); }
  };

  const setStatus = async (inv: ApiInvoice, status: string) => {
    try { await mutate(`/api/invoices/${inv.id}`, { status }); push({ tone: "primary", title: `${inv.ref} → ${status}` }); reload(); if (detail?.id === inv.id) setDetail({ ...detail, status }); }
    catch (e) { push({ tone: "danger", title: "Update failed", desc: e instanceof Error ? e.message : String(e) }); }
  };

  const issueFromQuote = async (q: ApiQuote) => {
    setBusy(true);
    try {
      const res = await fetch(`/api/quotes/${q.id}/invoice`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ due: new Date(Date.now() + 864e5 * 14).toISOString().slice(0, 10) }) });
      if (!res.ok) throw new Error((await res.json()).error ?? "failed");
      const inv = (await res.json()) as ApiInvoice;
      push({ tone: "success", title: `${inv.ref} issued from ${q.ref}`, desc: `${q.customer} · ${fmtPKR(inv.total)}` });
      setIssueOpen(false); reload();
    } catch (e) { push({ tone: "danger", title: "Could not issue invoice", desc: e instanceof Error ? e.message : String(e) }); }
    finally { setBusy(false); }
  };

  const cols: Column<ApiInvoice>[] = [
    { key: "ref", header: "Invoice", cell: (r) => (
      <span className="flex items-center gap-2.5">
        <span className="grid h-8 w-8 place-items-center rounded-control bg-primary-50 text-primary-700"><Receipt size={15} /></span>
        <span><span className="block text-small font-semibold text-ink">{r.ref}</span>
        <span className="block text-caption text-subtle">{r.orderId ? `order #${r.orderId}` : r.quoteId ? `quote #${r.quoteId}` : "manual"} · {timeAgo(r.createdAt)}</span></span>
      </span>) },
    { key: "customer", header: "Customer", cell: (r) => <span className="text-small text-slate-700">{r.customer}</span> },
    { key: "total", header: "Total", align: "right", cell: (r) => <span className="text-small font-semibold text-ink">{fmtPKR(r.total)}</span> },
    { key: "paid", header: "Paid", align: "right", cell: (r) => <span className={cn("text-small", r.paid > 0 ? "text-success-strong" : "text-subtle")}>{fmtPKR(r.paid)}</span> },
    { key: "balance", header: "Balance", align: "right", cell: (r) => <span className={cn("text-small font-semibold", r.balance > 0 ? "text-warning-strong" : "text-ink")}>{fmtPKR(r.balance)}</span> },
    { key: "due", header: "Due", cell: (r) => <span className="text-caption text-muted">{fmtDate(r.due)}</span> },
    { key: "status", header: "Status", cell: (r) => <StatusBadge status={r.status} /> },
    { key: "act", header: "", align: "right", cell: (r) => (
      <span className="flex justify-end gap-1.5">
        <Button size="sm" variant="secondary" onClick={() => void openDetail(r)}><FileText size={13} /> View</Button>
        {r.balance > 0 && r.status !== "Cancelled" && (
          <Button size="sm" variant="danger" onClick={() => void setStatus(r, "Cancelled")} title="Cancel invoice">✕</Button>)}
      </span>) },
  ];

  const stats = [
    { label: "Collected", value: fmtPKR(data?.collected ?? 0), tone: "text-success-strong" },
    { label: "Outstanding", value: fmtPKR(data?.outstanding ?? 0), tone: "text-warning-strong" },
    { label: "Invoices", value: String(data?.total ?? 0), tone: "text-ink" },
  ];

  return (
    <div>
      <PageHeader
        crumbs={[{ label: "Sales", to: "/quotations" }, { label: "Invoices" }]}
        title="Invoices & Payments"
        description="Quote → order → invoice → payment, with the 50% advance rule and printable PKR documents."
        actions={<><Button variant="secondary" onClick={reload}>Refresh</Button>
          <Button onClick={() => setIssueOpen(true)}><Send size={15} /> Invoice from quote</Button></>}
      />

      <div className="mb-4 grid grid-cols-1 gap-3 sm:grid-cols-3 lg:gap-4">
        {stats.map((s) => (
          <Card key={s.label} className="py-4">
            <p className="text-caption font-medium text-subtle uppercase">{s.label}</p>
            <p className={cn("mt-1 text-h2", s.tone)}>{s.value}</p>
          </Card>
        ))}
      </div>

      <Card>
        <div className="flex flex-wrap items-center gap-1.5 border-b border-hairline px-4 py-3">
          {FILTERS.map((f) => (
            <button key={f} onClick={() => setFilter(f)}
              className={cn("rounded-control px-3 py-1.5 text-caption font-semibold capitalize transition-colors",
                filter === f ? "bg-primary-600 text-white" : "text-muted hover:bg-surface-secondary hover:text-ink")}>
              {f === "all" ? "All" : f}
            </button>
          ))}
        </div>
        {error ? <div className="p-4"><ErrorState title="Invoices unavailable" debug="GET /api/invoices" onRetry={reload} /></div>
          : loading ? <SkeletonRows rows={5} />
          : (data?.items.length ?? 0) === 0 ? <div className="p-6"><EmptyState icon={<Receipt size={20} />} title="No invoices here" description="Issue one from an approved quote, or invoice a checked-out order directly." /></div>
          : <DataTable rows={data!.items} columns={cols} perPage={8} />}
      </Card>

      {/* Detail + payment modal */}
      <Modal open={!!detail} onClose={() => setDetail(null)} title={detail ? `${detail.ref} · ${detail.customer}` : ""}
        description={detail ? `${fmtPKR(detail.paid)} paid of ${fmtPKR(detail.total)} — balance ${fmtPKR(detail.balance)}` : undefined}
        className="max-w-2xl"
        footer={detail && (
          <><Button variant="secondary" onClick={() => printInvoice(detail)}><Printer size={14} /> Print / PDF</Button>
            {detail.balance > 0 && <Button onClick={() => void recordPayment()} disabled={busy || !Number(pay.amount)}><Banknote size={14} /> Record payment</Button>}</>
        )}>
        {detail && (
          <div className="space-y-4">
            <table className="w-full text-small">
              <thead><tr className="border-b border-hairline text-left text-caption text-subtle uppercase"><th className="py-1.5">Item</th><th className="py-1.5 text-right">Qty</th><th className="py-1.5 text-right">Amount</th></tr></thead>
              <tbody>{detail.items.map((i, n) => (
                <tr key={n} className="border-b border-hairline/60"><td className="py-1.5">{i.name ?? "Item"}</td><td className="py-1.5 text-right">{i.qty ?? 1}</td><td className="py-1.5 text-right">{fmtPKR((i.price ?? 0) * (i.qty ?? 1))}</td></tr>))}</tbody>
            </table>
            <div className="flex flex-wrap gap-x-8 gap-y-1 text-caption text-muted">
              <span>Subtotal <b className="text-ink">{fmtPKR(detail.subtotal)}</b></span>
              <span>Tax <b className="text-ink">{fmtPKR(detail.tax)}</b></span>
              <span>Shipping <b className="text-ink">{fmtPKR(detail.shipping)}</b></span>
              <span>Due date <b className="text-ink">{fmtDate(detail.due)}</b></span>
            </div>
            <div>
              <p className="mb-1.5 text-caption font-semibold uppercase text-subtle">Payments</p>
              {detail.payments.length === 0 ? <p className="text-caption text-muted">None yet — 50% advance is required before production starts.</p> : (
                <ul className="space-y-1">{detail.payments.map((p) => (
                  <li key={p.id} className="flex items-center justify-between rounded-control bg-surface-secondary px-3 py-1.5 text-caption">
                    <span><b className="text-ink">{fmtPKR(p.amount)}</b> · {p.method}{p.reference ? ` · ${p.reference}` : ""}</span>
                    <span className="text-subtle">{p.created_at.slice(0, 10)}</span>
                  </li>))}</ul>)}
            </div>
            {detail.balance > 0 && (
              <div className="grid grid-cols-1 gap-3 rounded-control border border-dashed border-hairline p-3 sm:grid-cols-3">
                <Field label="Amount (PKR)"><Input type="number" min={1} max={detail.balance} value={pay.amount} onChange={(e) => setPay((p) => ({ ...p, amount: e.target.value }))} /></Field>
                <Field label="Method"><Select value={pay.method} onChange={(e) => setPay((p) => ({ ...p, method: e.target.value }))}>
                  {["Bank transfer", "Cash", "Cheque", "JazzCash", "EasyPaisa", "Card"].map((m) => <option key={m}>{m}</option>)}</Select></Field>
                <Field label="Reference"><Input value={pay.reference} onChange={(e) => setPay((p) => ({ ...p, reference: e.target.value }))} placeholder="TRX-…" /></Field>
              </div>)}
            <Badge tone="primary" dot={false}>live · shared backend</Badge>
          </div>)}
      </Modal>

      {/* Issue-from-quote modal */}
      <Modal open={issueOpen} onClose={() => setIssueOpen(false)} title="Invoice from quotation" description="Approved and in-flight quotes become one-click invoices." footer={null} className="max-w-xl">
        {issuable.length === 0 ? <EmptyState icon={<FileText size={20} />} title="No issuable quotes" description="Move a quote to Approved in the pipeline first." /> : (
          <ul className="divide-y divide-hairline">{issuable.map((q) => (
            <li key={q.id} className="flex items-center justify-between gap-3 py-2.5">
              <span><span className="block text-small font-semibold text-ink">{q.ref} · {q.customer}</span>
                <span className="text-caption text-subtle"><StatusBadge status={q.status} /> · {fmtPKR(q.total)}</span></span>
              <Button size="sm" disabled={busy} onClick={() => void issueFromQuote(q)}><Send size={13} /> Issue</Button>
            </li>))}</ul>)}
      </Modal>
    </div>
  );
}
