-- ═══════════════════════════════════════════════════════════════════════
-- WOODEX platform · Postgres schema v1 (Supabase-compatible)
-- 1:1 semantic mirror of apps/api SQLite (server.mjs §schema). TEXT stays TEXT
-- deliberately: the app writes ISO-8601 strings and compares/sorts them, so
-- lexicographic TEXT ordering keeps every query's behavior identical.
-- INTEGER PRIMARY KEY AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY
-- (BY DEFAULT so the migrator can insert explicit ids, then setvals).
-- Shims at the bottom make existing SQLite-flavored SQL run unchanged.
-- ═══════════════════════════════════════════════════════════════════════
SET client_min_messages = warning;

CREATE TABLE IF NOT EXISTS products(
  id TEXT PRIMARY KEY, json TEXT NOT NULL, price DOUBLE PRECISION NOT NULL,
  in_stock INTEGER NOT NULL DEFAULT 1, stock_qty INTEGER NOT NULL DEFAULT 99,
  updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS materials(id TEXT PRIMARY KEY, json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS services(id TEXT PRIMARY KEY, json TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS leads(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ref TEXT, name TEXT NOT NULL, company TEXT,
  interest TEXT, source TEXT, contact TEXT, status TEXT DEFAULT 'New', owner TEXT,
  note TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS quotes(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ref TEXT, customer TEXT NOT NULL, contact TEXT,
  items TEXT NOT NULL, total DOUBLE PRECISION NOT NULL DEFAULT 0, status TEXT DEFAULT 'Draft',
  source TEXT DEFAULT 'storefront', note TEXT, audit TEXT DEFAULT '[]',
  created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS orders(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ref TEXT, customer TEXT NOT NULL, items TEXT NOT NULL,
  total DOUBLE PRECISION NOT NULL DEFAULT 0, status TEXT DEFAULT 'In Progress', stage TEXT DEFAULT 'production',
  owner TEXT DEFAULT 'Faisal', due TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS invoices(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ref TEXT, quote_id BIGINT, order_id BIGINT,
  customer TEXT NOT NULL, items TEXT NOT NULL DEFAULT '[]',
  subtotal DOUBLE PRECISION NOT NULL DEFAULT 0, discount DOUBLE PRECISION NOT NULL DEFAULT 0, tax DOUBLE PRECISION NOT NULL DEFAULT 0,
  shipping DOUBLE PRECISION NOT NULL DEFAULT 0, total DOUBLE PRECISION NOT NULL DEFAULT 0, paid DOUBLE PRECISION NOT NULL DEFAULT 0,
  status TEXT DEFAULT 'Issued', due TEXT, notes TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS payments(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, invoice_id BIGINT NOT NULL, amount DOUBLE PRECISION NOT NULL,
  method TEXT DEFAULT 'Bank transfer', reference TEXT, note TEXT, created_at TEXT);
CREATE TABLE IF NOT EXISTS returns(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ref TEXT, order_id BIGINT, customer TEXT,
  item TEXT, reason TEXT, state TEXT DEFAULT 'Requested', refund_amount DOUBLE PRECISION DEFAULT 0,
  resolution TEXT, created_at TEXT, updated_at TEXT);

CREATE TABLE IF NOT EXISTS clients(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, company TEXT, email TEXT, email_norm TEXT,
  phone TEXT, phone_norm TEXT, city TEXT, tags TEXT DEFAULT '[]', notes TEXT, source TEXT,
  merged_into BIGINT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS client_links(client_id BIGINT NOT NULL, entity TEXT NOT NULL, entity_id BIGINT NOT NULL,
  UNIQUE(entity, entity_id));
CREATE INDEX IF NOT EXISTS idx_client_links_client ON client_links(client_id, entity);
CREATE TABLE IF NOT EXISTS tasks(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_id BIGINT, lead_id BIGINT, quote_id BIGINT, order_id BIGINT,
  title TEXT NOT NULL, due TEXT, owner TEXT DEFAULT 'You', priority TEXT DEFAULT 'normal', done INTEGER DEFAULT 0,
  created_at TEXT, updated_at TEXT);

CREATE TABLE IF NOT EXISTS pages(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, slug TEXT UNIQUE NOT NULL, title TEXT NOT NULL,
  status TEXT DEFAULT 'Draft', seo_title TEXT, seo_desc TEXT, created_at TEXT, updated_at TEXT, theme TEXT);
CREATE TABLE IF NOT EXISTS page_blocks(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, page_id BIGINT NOT NULL, type TEXT NOT NULL,
  props TEXT NOT NULL DEFAULT '{}', sort INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_page_blocks_page ON page_blocks(page_id, sort);
CREATE TABLE IF NOT EXISTS page_versions(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, page_id BIGINT NOT NULL, snapshot TEXT NOT NULL,
  note TEXT, who TEXT DEFAULT 'You', created_at TEXT);
CREATE TABLE IF NOT EXISTS saved_sections(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, category TEXT DEFAULT 'Custom',
  tags TEXT DEFAULT '[]', block TEXT NOT NULL, created_at TEXT, updated_at TEXT);

CREATE TABLE IF NOT EXISTS track_events(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, page_id BIGINT, slug TEXT NOT NULL,
  kind TEXT NOT NULL, label TEXT, href TEXT, cid TEXT, ref TEXT,
  utm_source TEXT, utm_medium TEXT, utm_campaign TEXT, pct INTEGER,
  created_at TEXT);
CREATE INDEX IF NOT EXISTS idx_track_slug ON track_events(slug, kind, created_at);
CREATE INDEX IF NOT EXISTS idx_track_page ON track_events(page_id, kind, created_at);

CREATE TABLE IF NOT EXISTS conversations(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, client_id BIGINT NOT NULL UNIQUE,
  status TEXT DEFAULT 'open', assignee TEXT, priority INTEGER DEFAULT 0,
  unread INTEGER DEFAULT 0, last_at TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS messages(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversation_id BIGINT NOT NULL,
  channel TEXT NOT NULL, direction TEXT DEFAULT 'outbound', author TEXT,
  body TEXT NOT NULL, meta TEXT, created_at TEXT);
CREATE INDEX IF NOT EXISTS idx_msg_conv ON messages(conversation_id, id);

CREATE TABLE IF NOT EXISTS users(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT UNIQUE NOT NULL, name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer', pass_salt TEXT, pass_hash TEXT,
  active INTEGER DEFAULT 1, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id BIGINT NOT NULL, created_at TEXT, expires_at TEXT);
CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY, value TEXT);

/* ── SQLite-compatibility shims: let the existing SQL run unchanged ── */
CREATE OR REPLACE FUNCTION datetime(t TEXT) RETURNS TIMESTAMP
  LANGUAGE sql IMMUTABLE PARALLEL SAFE AS
$$ SELECT NULLIF(t,'')::timestamp $$;
-- GROUP_CONCAT(x) (comma-joined) as used by the merge-review query
CREATE OR REPLACE FUNCTION wx_gc_trans(state TEXT[], v TEXT) RETURNS TEXT[]
  LANGUAGE sql IMMUTABLE PARALLEL SAFE AS
$$ SELECT CASE WHEN v IS NULL THEN state ELSE state || v END $$;
CREATE OR REPLACE FUNCTION wx_gc_final(state TEXT[]) RETURNS TEXT
  LANGUAGE sql IMMUTABLE PARALLEL SAFE AS
$$ SELECT CASE WHEN state IS NULL THEN NULL ELSE array_to_string(state, ',') END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
                 WHERE n.nspname='current_schema' AND p.proname='group_concat') THEN
    CREATE AGGREGATE group_concat(TEXT) (SFUNC=wx_gc_trans, STYPE=TEXT[], FINALFUNC=wx_gc_final, INITCOND='{}');
  END IF;
END $$;

/* ── Tenancy / RLS placeholder (PRD P2 — enable when tenants land) ──
   ALTER TABLE leads ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1;  (× all business tables)
   ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
   CREATE POLICY tenant_isolation ON leads USING (tenant_id = current_setting('app.tenant_id')::bigint);
   The application role stays a plain owner role until then — single tenant Woodex. */
